name: Continuous Integration

on:
  workflow_dispatch:
    
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  schedule:
    # Test latest versions once a month
    - cron: '30 8 15 * *'

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  test-action-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Test setup-powershell-yaml with latest version
        id: test-action-latest
        uses: ./

      - name: Print output
        run: |
          echo "${{ steps.test-action-latest.outputs.version }}"

      - name: Use powershell-yaml
        run: |
          $data = "hello: world"
          $yml = ConvertFrom-Yaml -Yaml "$data"
          $json = ConvertTo-Yaml -JsonCompatible -Data $yml;
          echo $json

  test-action-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Test setup-powershell-yaml with set version
        id: test-action-latest
        uses: ./
        with:
          version: '0.4.12'

      - name: Print output
        run: |
          echo "${{ steps.test-action-latest.outputs.version }}"

      - name: Use powershell-yaml
        run: |
          $data = "hello: world"
          $yml = ConvertFrom-Yaml -Yaml "$data"
          $json = ConvertTo-Yaml -JsonCompatible -Data $yml;
          echo $json
