name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - dev
      - main

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: pwsh

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test setup-powershell-yaml with latest version
        id: test-action-latest
        uses: ./

      - name: Print output
        run: |
          echo "${{ steps.test-action-latest.outputs.version }}"

      - name: Use powershell-yaml
        run: |
          $data = "hello: world"
          $yml = ConvertFrom-Yaml -Yaml "$data"
          $json = ConvertTo-Yaml -JsonCompatible -Data $yml;

      - name: Delete the cache
        if: steps.test-action-latest.outputs.cache-hit == 'true'
        run: |
          gh api `
            --method DELETE `
            -H "Accept: application/vnd.github+json" `
            -H "X-GitHub-Api-Version: 2022-11-28" `
            /repos/${{ github.repository }}/actions/caches?key=${{ steps.test-action-latest.outputs.cache-key }}
