name: Continuous Integration

on:
  workflow_dispatch:
    
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  test-action-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test setup-powershell-yaml with latest version
        id: test-action-latest
        uses: ./

      - name: Print output
        run: |
          echo "${{ steps.test-action-latest.outputs.version }}"

      - name: Use powershell-yaml
        run: |
          $data = "hello: world"
          $yml = ConvertFrom-Yaml -Yaml "$data"
          $json = ConvertTo-Yaml -JsonCompatible -Data $yml;
          echo $json

  test-action-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test setup-powershell-yaml with set version
        id: test-action-latest
        uses: ./
        with:
          version: '0.4.12'

      - name: Print output
        run: |
          echo "${{ steps.test-action-latest.outputs.version }}"

      - name: Use powershell-yaml
        run: |
          $data = "hello: world"
          $yml = ConvertFrom-Yaml -Yaml "$data"
          $json = ConvertTo-Yaml -JsonCompatible -Data $yml;
          echo $json
